package main.java;

/*
WATTWISE APPLICATION (ENTERPRISE)
TOPIC: PROBLEMS ENCOUNTERED BY UTILITY COMPANIES

WATTWISE IS A COMPREHENSIVE ENTERPRISE-LEVEL APPLICATION DESIGNED TO ADDRESS
THE COMMON PROBLEMS FACED BY ELECTRIC UTILITY DISTRIBUTION COMPANIES. 

AS ELECTRIC PROVIDERS STRUGGLE WITH ISSUES LIKE BILLING INACCURACIES, 
OUTAGE MISCOMMUNICATION, DELAYED COMPLAINT RESPONSES, AND INEFFICIENT 
DATA TRACKING, WATTWISE STEPS IN AS A SMART DIGITAL SOLUTION.

THE APPLICATION OFFERS A CENTRALIZED PLATFORM WHERE BOTH CUSTOMERS AND 
ADMINISTRATORS CAN MANAGE ESSENTIAL UTILITY SERVICES EFFICIENTLY. IT AUTOMATES 
METER READING, PROVIDES REAL-TIME OUTAGE UPDATES, MANAGES CUSTOMER COMPLAINTS 
THROUGH A TICKETING SYSTEM, MAKING IT A POWERFUL TOOL IN THE DIGITAL TRANSFORMATION OF ELECTRIC DISTRIBUTION SERVICES.

DEVELOPED BY: CARL FRANCIS T. ENCALLADO (BSCPe II - GF)
*/

// WATTWISE_MAINCLASS: MAIN ENTRY POINT OF THE APPLICATION
public class WattWise_mainClass {

	// MAIN METHOD: LAUNCHES LOGIN PAGE, NO PARAMETERS, THROWS EXCEPTION, RETURNS VOID
	public static void main(String[] args) throws Exception {
		new WattWise_LogInPage();
	}
}
